### PR TITLE
tests: added journal logs fetch feature for functional tests

### LINKED ISSUE #1565: tests: automatically fetch systemd-nspawn jounal logs when functional tests are failed
Sometimes functional tests are failed for an unknown reason. In these cases automatic logs fetching could help to debug the problem.
/cc @tixxdz @jonboulle @dongsupark

### PR DESCRIPTION
**Pull request by kayrus**
resolves #1565
/cc @tixxdz @jonboulle @dongsupark

### CODE REVIEW

**Comment by kayrus** [comment]
TODO:
* add function name of the failed test before printing the logs.
* print separate fleetd logs.

**Comment by dongsupark** [comment]
Looks good, and it works.
As this PR changes various places in functional tests, I think this PR needs to be merged prior to other minor changes. Otherwise afterwards we could see unexpected merge conflicts.

**Comment by dongsupark** [comment]
Hmm, with this PR, ``TestSingleNodeConnectivityLoss`` seems to fail with a message like below. This looks like a new one. Isn't it maybe because cluster was destroyed too early?

```
--- FAIL: TestSingleNodeConnectivityLoss (25.83s)
    connectivity-loss_test.go:216: Failed to retrieve journal: exit status 1
```

**Comment by kayrus** [comment]
Fixed functional tests.

**Comment by dongsupark** [comment]
@kayrus Cool! My local test also passes.

**Comment by tixxdz** [comment]
lgtm, thanks!

**Pull request merged**
