### PR TITLE
Godeps: bump etcd deps

### LINKED ISSUE #1336: etcd/client: use new version that randomizes clients
A large number of fleetd members pointed at the same etcd list will put all load on the first etcd member in that list. We need to fix the etcd client to randomize this list which depends on: https://github.com/coreos/etcd/issues/3386

### PR DESCRIPTION
**Pull request by mischief**
fixes #1336

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM. But have you verified this change does fix https://github.com/coreos/fleet/issues/1336?

**Comment by mischief** [comment]
@xiang90 no. don't merge yet.

**Comment by mischief** [comment]
@xiang90 @philips verified the change with etcd's goreman Procfile and wireshark.

**Comment by xiang90** [comment]
Thanks! Let us get it merged.

**Comment by vcaputo** [comment]
1337!

**Pull request merged**
