### PR TITLE
fleetctl:test: improve the start test and make sure that it handles templates

### PR DESCRIPTION
**Pull request by tixxdz**
Patch 1: This is a preparation patch for the next start test patch that will try to create and start units from a template unit.

Patch 2: improve the start test and make sure that it handles templates

### CODE REVIEW

**Comment by jonboulle** [comment]
Waiting on semaphore to be fixed..

**Comment by tixxdz** [comment]
@jonboulle  https://github.com/coreos/fleet/pull/1467

**Comment by tixxdz** [comment]
tests pass, thanks!

**Comment by dongsupark** [comment]
Looks good, it works.
Actually a pending PR #1473 and a new update of #1461 depend on this PR #1461. So I hope that #1461 could be first merged.

**Pull request merged**
