### PR TITLE
Godeps: bump godbus and go-systemd

### LINKED ISSUE #992: systemd hides the fact that there exists a maximum unit file line length
Hello, 

I think that the ExecStart in the unit files has a limitation with the length of the command. It cuts the command and indicates  "Missing '='.

Does this limit exists really ?

This is the error: 

```
Oct 21 22:01:44 ip-172-31-20-195.ec2.internal systemd[1]: [/run/fleet/units/e-88747910-a986-4ed0-9b10-3af9.minion.service:9] Missing '='.
Oct 21 22:01:45 ip-172-31-20-195.ec2.internal systemd[1]: [/run/fleet/units/e-88747910-a986-4ed0-9b10-3af9.minion.service:8] String is not UTF-8 clean, ignoring assignment: /bin/sh -c "while true; do ; /usr/bin/sleep 3; public_ipv4=$COREOS_PUBLIC_IPV4;  e88747910a9864ed09b103af9_8181=$(docker port e-88747910-a986-4ed0-9b10-3af9 8181 | cut -d ':' -f 2 ); e88747910a9864ed09b103af9_8101=$(docker port e-88747910-a986-4ed0-9b10-3af9 8101 | cut -d ':' -f 2 ); e88747910a9864ed09b103af9_4444=$(docker port e-88747910-a986-4ed0-9b10-3af9 4444 | cut -d ':' -f 2 ); e88747910a9864ed09b103af9_5555=$(docker port e-88747910-a986-4ed0-9b10-3af9 5555 | cut -d ':' -f 2 ); etcdctl set /_esb/user/john/instance/e-88747910-a986-4ed0-9b10-3af9 \"{\\\"ID\\\":\\\"e-88747910-a986-4ed0-9b10-3af9\\\",\\\"Labels\\\":{\\\"owner\\\":\\\"john\\\"},\\\"Created\\\":\\\"Tuesday, 21-Oct-14 21:53:59 UTC\\\",\\\"State\\\":\\\"running\\\",\\\"IP\\\":\\\"$public_ipv4\\\",\\\"Configuration\\\":{\\\"CPU_SHARED\\\":\\\"\\\",\\\"ESB\\\":\\\"servicemix\\\",\\\"Features\\\":[\\\"camel-sql\\\"],\\\"ID\\\":\\\"i-124691ed-f613-4ea5-ab6b-05c7\\\",\\\"JBI_allowCoreThreadTimeOut\\\":\\\"true\\\",\\\"JBI_corePoolSize\\\":\\\"4\\\",\\\"JBI_keepAliveTime\\\":\\\"60000\\\",\\\"JBI_maximumPoolSize\\\":\\\"-1\\\",\\\"JBI_queueSize\\\":\\\"1024\\\",\\\"JBI_shutdownTimeout\\\":\\\"0\\\",\\\"JVM_MAX_MEM\\\":\\\"\\\",\\\"JVM_MAX_PERM_MEM\\\":\\\"\\\",\\\"JVM_MIN_MEM\\\":\\\"\\\",\\\"JVM_PERM_MEM\\\":\\\"\\\",\\\"MAX_MEM\\\":\\\"\\\",\\\"NMR_allowCoreThreadTimeOut\\\":\\\"true\\\",\\\"NMR_corePoolSize\\\":\\\"4\\\",\\\"NMR_keepAliveTime\\\":\\\"60000\\\",\\\"NMR_maximumPoolSize\\\":\\\"-1\\\",\\\"NMR_queueSize\\\":\\\"1024\\\",\\\"NMR_shutdownTimeout\\\":\\\"0\\\",\\\"Name\\\":\\\"\\\",\\\"Ports\\\":{\\\"endpoint1\\\":4444,\\\"endpoint2\\\":5555},\\\"SERVICEMIX_PASSWORD\\\":\\\"smx\\\",\\\"SERVICEMIX_USER\\\":\\\"smx\\\"},\\\"PortBindings\\\":{\\\"4444\\\":\\\"$e88747910a9864ed09b103af9_4444\\\",\\\"5555\\\":\\\"$e88747910a9864ed09b103af9_5555\\\",\\\"8101\\\":\\\"$e88747910a9864ed09b103af9_8101\\\",\\\"8181\\\":\\\"$e88747910a9864ed09b103af9_8181\\\"},\\\"UserAccess\\\":{\\\"Karaf Console\\\":\\\"$public_ipv4$e88747910a9864ed09b103af
```

And this is the unit file: 

```
[Unit]
Description=Info docker e-88747910-a986-4ed0-9b10-3af9 ESB Instance
After=e-88747910-a986-4ed0-9b10-3af9.service
Requires=e-88747910-a986-4ed0-9b10-3af9.service

[Service]
EnvironmentFile=/etc/environment
ExecStart=/bin/sh -c "while true; do ; /usr/bin/sleep 3; public_ipv4=$COREOS_PUBLIC_IPV4;  e88747910a9864ed09b103af9_8181=$(docker port e-88747910-a986-4ed0-9b10-3af9 8181 | cut -d ':' -f 2 ); e88747910a9864ed09b103af9_8101=$(docker port e-88747910-a986-4ed0-9b10-3af9 8101 | cut -d ':' -f 2 ); e88747910a9864ed09b103af9_4444=$(docker port e-88747910-a986-4ed0-9b10-3af9 4444 | cut -d ':' -f 2 ); e88747910a9864ed09b103af9_5555=$(docker port e-88747910-a986-4ed0-9b10-3af9 5555 | cut -d ':' -f 2 ); etcdctl set /_esb/user/john/instance/e-88747910-a986-4ed0-9b10-3af9 \"{\\\"ID\\\":\\\"e-88747910-a986-4ed0-9b10-3af9\\\",\\\"Labels\\\":{\\\"owner\\\":\\\"john\\\"},\\\"Created\\\":\\\"Tuesday, 21-Oct-14 21:53:59 UTC\\\",\\\"State\\\":\\\"running\\\",\\\"IP\\\":\\\"$public_ipv4\\\",\\\"Configuration\\\":{\\\"CPU_SHARED\\\":\\\"\\\",\\\"ESB\\\":\\\"servicemix\\\",\\\"Features\\\":[\\\"camel-sql\\\"],\\\"ID\\\":\\\"i-124691ed-f613-4ea5-ab6b-05c7\\\",\\\"JBI_allowCoreThreadTimeOut\\\":\\\"true\\\",\\\"JBI_corePoolSize\\\":\\\"4\\\",\\\"JBI_keepAliveTime\\\":\\\"60000\\\",\\\"JBI_maximumPoolSize\\\":\\\"-1\\\",\\\"JBI_queueSize\\\":\\\"1024\\\",\\\"JBI_shutdownTimeout\\\":\\\"0\\\",\\\"JVM_MAX_MEM\\\":\\\"\\\",\\\"JVM_MAX_PERM_MEM\\\":\\\"\\\",\\\"JVM_MIN_MEM\\\":\\\"\\\",\\\"JVM_PERM_MEM\\\":\\\"\\\",\\\"MAX_MEM\\\":\\\"\\\",\\\"NMR_allowCoreThreadTimeOut\\\":\\\"true\\\",\\\"NMR_corePoolSize\\\":\\\"4\\\",\\\"NMR_keepAliveTime\\\":\\\"60000\\\",\\\"NMR_maximumPoolSize\\\":\\\"-1\\\",\\\"NMR_queueSize\\\":\\\"1024\\\",\\\"NMR_shutdownTimeout\\\":\\\"0\\\",\\\"Name\\\":\\\"\\\",\\\"Ports\\\":{\\\"endpoint1\\\":4444,\\\"endpoint2\\\":5555},\\\"SERVICEMIX_PASSWORD\\\":\\\"smx\\\",\\\"SERVICEMIX_USER\\\":\\\"smx\\\"},\\\"PortBindings\\\":{\\\"4444\\\":\\\"$e88747910a9864ed09b103af9_4444\\\",\\\"5555\\\":\\\"$e88747910a9864ed09b103af9_5555\\\",\\\"8101\\\":\\\"$e88747910a9864ed09b103af9_8101\\\",\\\"8181\\\":\\\"$e88747910a9864ed09b103af9_8181\\\"},\\\"UserAccess\\\":{\\\"Karaf Console\\\":\\\"$public_ipv4$e88747910a9864ed09b103af9_8101\\\",\\\"Web Console\\\":\\\"http://$public_ipv4:$e88747910a9864ed09b103af9_8181/system/console\\\"},\\\"Error\\\":\\\"\\\"}\" --ttl 90; /usr/bin/sleep 30; done"
ExecStop=/usr/bin/echo stopped

[X-Fleet]
MachineOf=e-88747910-a986-4ed0-9b10-3af9.service
```

### PR DESCRIPTION
**Pull request by jonboulle**
Fixes #992

### CODE REVIEW

**Comment by jonboulle** [comment]
@ecnahc515 what is the actual problem you saw with this? can you provide a case to reproduce?

**Comment by mischief** [comment]
i think the interest here is in coreos/go-systemd#108 to fix #992.

**Comment by jonboulle** [comment]
I understand that (see OP), but out of band Chance expressed concern that
this patch caused other issues, so I want to hear what they are

**Comment by ecnahc515** [comment]
@jonboulle When I submit a unit with a line longer than 2048 characters, its submitted successfully but the unit can't be listed or destroyed and fleet continues to spew errors in it's logs about the unit not being able to be validated. So it's basically stuck in fleet once you submit it. Validation should be rejecting it before it gets into etcd, and ideally also on the client.

**Comment by jonboulle** [comment]
@ecnahc515 https://github.com/coreos/fleet/commit/db1fba58e601a3bf2d7bf1a7b7ee095632d09916

**Comment by jonboulle** [comment]
This is already checked in fleetctl so only applies to older or other clients.

**Comment by ecnahc515** [comment]
@jonboulle I just tested this, and it's not preventing submission of units with lines longer than 2048 bytes. It gets submitted, and I can remove it now, but fleet still trys to submit to systemd, and systemd has the errors from before: `Missing '='.`

**Comment by jonboulle** [comment]
@ecnahc515 want to test this with your scenario now?

**Comment by ecnahc515** [comment]
This fixes the issue, but the error message that told me specifically what the problem was has gotten more generic/worse:
```
core@core-01:~core@core-01 ~ $ /opt/bin/fleetctl start echo.service
Error creating units: error retrieving Unit(echo.service) from Registry: googleapi: got HTTP response code 500 with body: {"error":{"code":500,"message":""}}
core@core-01:~core@core-01 ~ $ /usr/bin/fleetctl start echo.service
Error creating units: error retrieving Unit(echo.service) from Registry: googleapi: got HTTP response code 500 with body: {"error":{"code":500,"message":""}}
```

**Comment by jonboulle** [comment]
That's not right..

**Comment by jonboulle** [comment]
@ecnahc515 I can't reproduce, can you please provide steps with shas and examples?

**Comment by ecnahc515** [comment]
Building fleet:
```
hub checkout https://github.com/coreos/fleet/pull/1375                                                                                                                                                           master
Branch jonboulle-ecnahc515-update_go_systemd set up to track remote branch ecnahc515-update_go_systemd from jonboulle.
Switched to a new branch 'jonboulle-ecnahc515-update_go_systemd'
~/g/s/g/c/fleet ❯❯❯ git pull                                                                                                                                                                          jonboulle-ecnahc515-update_go_systemd
Already up-to-date.
~/g/s/g/c/fleet ❯❯❯ ./build-docker                                                                                                                                                                    jonboulle-ecnahc515-update_go_systemd
~/g/s/g/c/fleet ❯❯❯ export DOCKER_HOST=172.17.8.101:2375                                                                                                                                            ⏎ jonboulle-ecnahc515-update_go_systemd
~/g/s/g/c/fleet ❯❯❯ docker ps                                                                                                                                                                         jonboulle-ecnahc515-update_go_systemd
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
~/g/s/g/c/fleet ❯❯❯ ./build-docker                                                                                                                                                                    jonboulle-ecnahc515-update_go_systemd
Building fleetd...
Building fleetctl...
````

Starting fleet and the problem unit on coreos-vagrant:
```
core@core-01:~core@core-01 ~ $ sudo systemctl stop fleet
core@core-01:~core@core-01 ~ $ sudo cp /Users/chance/go/src/github.com/coreos/fleet/bin/fleetd /opt/bin/fleetd
core@core-01:~core@core-01 ~ $ sudo cp /Users/chance/go/src/github.com/coreos/fleet/bin/fleetctl /opt/bin/fleetctl
core@core-01:~core@core-01 ~ $ sudo systemctl cat fleet
# /usr/lib64/systemd/system/fleet.service
[Unit]
Description=fleet daemon

After=etcd.service
After=etcd2.service

Wants=fleet.socket
After=fleet.socket

[Service]
Environment=GOMAXPROCS=1
ExecStart=/usr/bin/fleetd
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target

# /run/systemd/system/fleet.service.d/20-cloudinit.conf
[Service]
Environment="FLEET_METADATA=role=master"
Environment="FLEET_PUBLIC_IP=172.17.8.101"
# /etc/systemd/system/fleet.service.d/override.conf
[Service]
ExecStart=
ExecStart=/opt/bin/fleetd
core@core-01:~core@core-01 ~ $ sudo systemctl start fleet
core@core-01 ~ $ ps aux | grep fleet
root      1441  0.7  1.0  14192 10660 ?        Ssl  17:23   0:01 /opt/bin/fleetd
core@core-01:~core@core-01 ~ $ /opt/bin/fleetd --version
fleetd version 0.11.5+git
core@core-01:~core@core-01 ~ $ /opt/bin/fleetctl --version
fleetctl version 0.11.5+git
core@core-01:~core@core-01 ~ $ ls
echo.service
core@core-01:~core@core-01 ~ $ cat echo.service
# test unit file

[Service]
ExecStart=/usr/bin/echo \
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
Restart=always
RestartSec=10s

core@core-01:~core@core-01 ~ $ fleetctl list-unit-files
UNIT	HASH	DSTATE	STATE	TARGET
core@core-01:~core@core-01 ~ $ fleetctl list-units
UNIT	MACHINE	ACTIVE	SUB
core@core-01:~core@core-01 ~ $ fleetctl start echo.service
Error creating units: error retrieving Unit(echo.service) from Registry: googleapi: got HTTP response code 500 with body: {"error":{"code":500,"message":""}}
core@core-01:~core@core-01 ~ $ /opt/bin/fleetctl start echo.service
Error creating units: error retrieving Unit(echo.service) from Registry: googleapi: got HTTP response code 500 with body: {"error":{"code":500,"message":""}}
```

sha1sum:
```
core@core-01:~core@core-01 ~ $ sha1sum /opt/bin/{fleetctl,fleetd}
deaf9121c17779df218ea9242175c480bc15014c  /opt/bin/fleetctl
8af7450080ec5e317cb3cf57d56d2a4f3980e52e  /opt/bin/fleetd
```

Git commit: 1f9fe14fd2c925b920e3fe3e39ee16a5bceb5bfe

**Comment by jonboulle** [comment]
Please look in fleetd's log to see what the 500 actually is internally.

**Comment by ecnahc515** [comment]
@jonboulle It turns out that etcd still had the unit stored from a previous run prior to the fix, and despite it not showing in `fleetctl list-units` or `fleetctl list-unit-files` it was still in etcd. These logs indicated so:

```
Oct 14 21:55:26 core-01 fleetd[1441]: ERROR unit.go:72: error parsing Unit(23d83054699a61ecf2480a0cc5740ad1118e2e4b): line too long (max 2048 bytes)
Oct 14 21:55:26 core-01 fleetd[1441]: WARN job.go:268: No Unit found in Registry for Job(echo.service)
Oct 14 21:55:26 core-01 fleetd[1441]: ERROR job.go:108: Failed to parse Unit from etcd: unable to parse Unit in Registry at key /_coreos.com/fleet/job/echo.service/object
```

After deleting the fleet dir in etcd and restarting fleet with the latest commit fleetctl returns the proper results:

```
core@core-01:~core@core-01 ~ $ /opt/bin/fleetctl start echo.service
Error creating units: failed getting Unit(echo.service) from file: line too long (max 2048 bytes)
```

**Comment by sukrit007** [comment]
+1 for the fix. Kind of a blocker.

As far as the caching is considered, I am assuming that happens for the units that were previously deployed and failed due to line length issue..  Since  the units that exceed the  length limit would technically have never worked for anyone (prior to the fix), can we simply address this by documentation (cleaning up respective entry in etcd ?). 

My 2 cents :   Having this fix upstream sooner in alpha with workaround for existing units would be better off than waiting for a complete solution that addresses caching solution for unit files that do not currently work.

**Comment by jonboulle** [comment]
Any chance you could come up with an example of what the cleanup process
involves?

**Comment by antrik** [comment]
FWIW, all tests (unit and functional) still pass with this.

**Comment by jdeathe** [comment]
@jonboulle - I think the "cleanup process" mentioned by @sukrit007 was in reference to the following comment from @chancez. 

> After deleting the fleet dir in etcd and restarting fleet ...

In my case I don't have an issue with lines exceeding the line limit in my original template unit-files but I am affected by fleet converting the ExecStart string, (broken up with `\` characters), into a single line.

**Pull request merged**
