### PR TITLE
godep: updated golang.org/x/crypto/...

### LINKED ISSUE #565: handshake failed: ssh: unexpected message type 1 (expected 52)
I reported this on coreos/coreos-vagrant#106 but it also happens when trying to manage a cluster on EC2.

It happens when you have more than 7 keys in the ssh-agent. 

My ~/.ssh/config says what key should be used for that host but the ssh tunneling feature seems to ignore that.

### PR DESCRIPTION
**Pull request by kayrus**
resolves #565

### CODE REVIEW

**Comment by tixxdz** [comment]
@kayrus @jonboulle it seems that of the library tests (not related to fleet) were removed, where in upstream they are still there. Any hint on this ?

thanks!

**Comment by kayrus** [comment]
I suppose it is godep's behavior.

**Comment by kayrus** [comment]
I use go1.5.3 and godep v60. Even with `-t` godep doesn't preserve test files.

**Comment by jonboulle** [comment]
Not including tests is fine. I'm surprised `-t` doesn't work for you, sounds like a bug..

**Comment by jonboulle** [comment]
Thanks @kayrus ! LGTM

**Comment by kayrus** [comment]
@jonboulle yep, it is a bug https://github.com/tools/godep/issues/405

**Pull request merged**
