### PR TITLE
Revert "server,fleetctl: clean up duration calculation"

### PR DESCRIPTION
**Pull request by bcwaldon**
Reverts coreos/fleet#1176

### CODE REVIEW

**Comment by bcwaldon** [comment]
@crawford need an LGTM from you

**Comment by crawford** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm (the "g" stands for "terrible")

**Comment by crawford** [comment]
LGTM means "golang is the bane of my existence", if that wasn't clear.

**Comment by bcwaldon** [comment]
nice doing business with you @crawford

**Pull request merged**
