### PR TITLE
glide: use glide instead of govendor

### PR DESCRIPTION
**Pull request by dongsupark**
Use glide for package management, instead of govendor. Package management policy of fleet is to keep vendor files checked in as before, although glide also allows to remove the vendors from git repos.

Commands used for the conversion:

```
$ glide init
$ glide update --strip-vendor --strip-vcs --update-vendored --delete
$ glide vc --only-code --no-tests
```
 
Fixes: https://github.com/coreos/fleet/issues/1610

### CODE REVIEW

**Comment by hectorj2f** [comment]
+1 on this

**Comment by jonboulle** [comment]
:+1:

**Comment by dongsupark** [comment]
Updated.
* Removed ``github.com/gogo/protobuf`` and ``google.golang.org/grpc``. Adding grpc vendors in advance was a bad idea. That caused a lot of trouble when trying to update glide again. I'm going to add them later again when the grpc branch is merged.
* Added ``'--delete'`` option to glide update, to clean up unnecessary files.
* Added a helper script ``scripts/glide-update.sh``, inspired by rkt.

**Comment by dongsupark** [comment]
Rebased. I'll merge it soon, if there's no objection.

**Pull request merged**
