### PR TITLE
tests: remove install-vagrant-on-semaphore script

### PR DESCRIPTION
**Pull request by jonboulle**
We're not using this (instead, preferring the qemu approach), so remove
it for now to simplify.

### CODE REVIEW

**Comment by jonboulle** [comment]
Testing semaphore PR...

**Comment by jonboulle** [comment]
ruh? semaphore didn't run the setup properly.. https://semaphoreci.com/coreos/fleet/branches/pull-request-1463/builds/1

**Comment by jonboulle** [comment]
@kayrus any idea on the failure?

**Comment by kayrus** [comment]
@jonboulle fixed here: https://github.com/coreos/fleet/pull/1467

**Pull request merged**
