### PR TITLE
Shutdown fixes/improvements

### PR DESCRIPTION
**Pull request by antrik**
Rebased from https://github.com/coreos/fleet/pull/1067 , and added a test case to verify the fix.

Should fix https://github.com/coreos/fleet/issues/1369

### CODE REVIEW

**Comment by antrik** [comment]
Meh, the new test seems to fail intermittently now and then :-(

**Comment by jonboulle** [comment]
How do they fail?

**Comment by antrik** [comment]
@jonboulle in order to set the stage for triggering the condition we want to test, we first need to cut the network connection to etcd, and wait for the "Monitor triggered" message to show up in the journal. Sometimes this just waits forever. Don't know yet why this happens: whether we just miss the message for some reason; or whether fleet sometimes behaves differently, and the message is indeed not generated at all...

**Comment by antrik** [comment]
I should probably note that this seems to happen occasionally both with the original and with the reworked code.

**Comment by antrik** [comment]
OK, it turns out it was only my method of monitoring the journal that was unreliable -- with a different approach it appears to work better.

While at it, I added two extra commits to this PR, that are not strictly necessary, but related: one reduces the agent_ttl for fleet to speed up the new test; the other is a minor cleanup to the fleet code changed in this PR, which I stumbled upon while working on this stuff.

**Comment by tixxdz** [comment]
@antrik could you re-push again so the semaphore runs again ?

**Comment by antrik** [comment]
I guess Semaphore hates this PR :-( Let's try a new one...

**Comment by tixxdz** [comment]
Ok this one was closed in favor of #1496

**Pull request closed without merging**
