### PR TITLE
metrics: added prometheus metrics for fleet

### PR DESCRIPTION
**Pull request by kayrus**
@miekg I've rebased your old PR #1415 and updated godeps

### CODE REVIEW

**Comment by kayrus** [comment]
@joshix could you review docs?

**Comment by robszumski** [comment]
LGTM, but defer to @joshix

**Comment by joshix** [comment]
LGTM for purpose.

**Comment by joshix** [comment]
Supersedes #1415

**Comment by hectorj2f** [comment]
Nice 😉

**Comment by kayrus** [comment]
@jonboulle this PR is ready to be merged. I don't think tests are necessary for this functionality. At least I didn't find any metrics tests in etcd.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coreos/fleet] metrics: added p..." ]
>@jonboulle this PR is ready to be merged. I don't think tests are necessary for this functionality. At least I didn't find any metrics tests in etcd.

Testing this is pretty annoying, would be nice if prometheus would provide some
kind of metrics recorder that would make this easier...

**Comment by jonboulle** [comment]
LGTM but let's get v0.12.0 done first?

**Comment by tixxdz** [comment]
@jonboulle as discussed all v0.12.0 PRs and Issues have been handled!

**Comment by kayrus** [comment]
Blocked by https://github.com/coreos/fleet/pull/1537

**Comment by tixxdz** [comment]
Thanks all, this one was reviewed and already has lgtm! and it touches lot of parts of the code where other PRs may conflict with it. So merging this one and #1537 will be on top later when it's ready and reviewed.

**Pull request merged**
