### PR TITLE
[WIP] grpc + vendoring + functional test

### PR DESCRIPTION
**Pull request by dongsupark**
Just for testing grpc stuff together: #1426 + #1657 + #1656

### CODE REVIEW

**Comment by dongsupark** [comment]
Added 2 commits to get rid of travis errors: "vendor: remove vendor/google.golang.org/grpc/test" and "add license headers for gRPC source files". I'll create a new PR that contains the 2 commits.

**Comment by dongsupark** [comment]
All right. Every test passed, all relevant PRs were merged. So I'm closing it.

**Comment by kayrus** [comment]
@dongsupark @hectorj2f guys, you have to celebrate this event :)

**Comment by dongsupark** [comment]
@kayrus Yuhu! :-)
I've heard, Hector is already on vacation. I hope he already enjoys it. :-)

**Pull request closed without merging**
