### PR TITLE
agent/unit_state: print more verbosely in failure

### PR DESCRIPTION
**Pull request by jonboulle**
Testing test failure...

### CODE REVIEW

**Comment by jonboulle** [comment]
travis you're killing me

**Comment by jonboulle** [comment]
@mischief I think that #1351 might have actually "fixed" this; i.e. there was some kind of weird timing issue. I've never been able to reproduce the failure locally :/

**Comment by mischief** [comment]
@jonboulle are you using GOMAXPROCS>1 as travis does when this failure appears?

**Comment by jonboulle** [comment]
@mischief aha; I was using `GOMAXPROCS=4`, but with `GOMAXPROCS=2` I *can*!

**Comment by mischief** [comment]
uhuh.

```
mischief@delta ~/code/go/src/github.com/coreos/fleet/agent $ export GOMAXPROCS=4
mischief@delta ~/code/go/src/github.com/coreos/fleet/agent $ go test -c
mischief@delta ~/code/go/src/github.com/coreos/fleet/agent $ ./agent.test 
ERROR reconcile.go:215: Desired state and current state of Job(foo.service) nil, not sure what to do
ERROR reconcile.go:215: Desired state and current state of Job(foo.service) nil, not sure what to do
ERROR unit_state.go:216: Refusing to push UnitState(foo.service), no MachineID: &unit.UnitState{LoadState:"", ActiveState:"active", SubState:"", MachineID:"", UnitHash:"", UnitName:"foo.service"}
--- FAIL: TestUnitStatePublisherRunWithDelays-4 (0.00s)
        unit_state_test.go:650: bad toPublishStates: got map[string]*unit.UnitState{"foo.service":(*unit.UnitState)(0xc208078300), "bar.service":(*unit.UnitState)(0xc208078360), "baz.service":(*unit.UnitState)(0xc2080783c0)}, want map[string]*unit.UnitState{"foo.service":(*unit.UnitState)(0xc208078480), "bar.service":(*unit.UnitState)(0xc2080784e0), "baz.service":(*unit.UnitState)(0xc208078540)}
FAIL
```

**Comment by jonboulle** [comment]
guh

**Comment by jonboulle** [comment]
I found the issue but am not yet sure how to properly deal with it. In any event I'm landing this as it helps a little with debugging.

**Pull request merged**
