### PR TITLE
use vishvananada/netlink

### PR DESCRIPTION
**Pull request by reneengelhard**
I failed to use godep without overwriting all the stuff, so I did it manually....

### CODE REVIEW

**Comment by jonboulle** [comment]
Please don't do it manually. How are you invoking godep? what happens exactly?

**Comment by reneengelhard** [comment]
@jonboulle: ok, didn't want to bother you with this but as you asked.

From your link in the bug one should run godep restore. Let's do that.

`rene@endor:~/CoreOS/git/endocode/fleet$ git reset --hard 27cc0df4c882ef1a740275f3f8752fbc296f18db
HEAD ist jetzt bei 27cc0df Update netlink dependency (Closes: #1468)
rene@endor:~/CoreOS/git/endocode/fleet$ export GOPATH=`pwd`/Godeps/_workspace/
rene@endor:~/CoreOS/git/endocode/fleet$ ~/godep/godep restore
godep: error downloading dep (code.google.com/p/go-uuid/uuid): unable to detect version control system for code.google.com/ path
godep: Error downloading some deps. Aborting restore and check.
`

ok, sure, code.google.com is dead. let's try to edit it out.

`rene@endor:~/CoreOS/git/endocode/fleet$ ~/godep/godep restore
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/etcd/client; git checkout b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
fatal: Referenz ist kein "Tree"-Objekt: b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
godep: error restoring dep (github.com/coreos/etcd/client): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/etcd/pkg/pathutil; git checkout b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
fatal: Referenz ist kein "Tree"-Objekt: b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
godep: error restoring dep (github.com/coreos/etcd/pkg/pathutil): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/etcd/pkg/types; git checkout b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
fatal: Referenz ist kein "Tree"-Objekt: b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
godep: error restoring dep (github.com/coreos/etcd/pkg/types): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/go-semver/semver; git checkout a9a0c39c7e4a2929f73d4b757d1860fbb8e66d06
fatal: Referenz ist kein "Tree"-Objekt: a9a0c39c7e4a2929f73d4b757d1860fbb8e66d06
godep: error restoring dep (github.com/coreos/go-semver/semver): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/go-systemd/activation; git checkout 1f2251651d199b698a0be8c8bf2283178a2a97ed
fatal: Referenz ist kein "Tree"-Objekt: 1f2251651d199b698a0be8c8bf2283178a2a97ed
godep: error restoring dep (github.com/coreos/go-systemd/activation): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/go-systemd/dbus; git checkout 1f2251651d199b698a0be8c8bf2283178a2a97ed
fatal: Referenz ist kein "Tree"-Objekt: 1f2251651d199b698a0be8c8bf2283178a2a97ed
godep: error restoring dep (github.com/coreos/go-systemd/dbus): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/go-systemd/unit; git checkout 1f2251651d199b698a0be8c8bf2283178a2a97ed
fatal: Referenz ist kein "Tree"-Objekt: 1f2251651d199b698a0be8c8bf2283178a2a97ed
godep: error restoring dep (github.com/coreos/go-systemd/unit): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/docker/libcontainer/netlink; git checkout 8c0303d92862eccc4bb9a07d7dac9065e4a32014
fatal: Referenz ist kein "Tree"-Objekt: 8c0303d92862eccc4bb9a07d7dac9065e4a32014
godep: error restoring dep (github.com/docker/libcontainer/netlink): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/godbus/dbus; git checkout 9bb9dbf0e53309fa81d26e7230cbb6cff9373cad
fatal: Referenz ist kein "Tree"-Objekt: 9bb9dbf0e53309fa81d26e7230cbb6cff9373cad
godep: error restoring dep (github.com/godbus/dbus): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork; git checkout b473f398c464f1988327f67c9e6aa7fba62f80d2
fatal: Referenz ist kein "Tree"-Objekt: b473f398c464f1988327f67c9e6aa7fba62f80d2
godep: error restoring dep (github.com/jonboulle/clockwork): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/rakyll/globalconf; git checkout fd9ff89130a682478a0c94e893ff4affe570b002
fatal: Referenz ist kein "Tree"-Objekt: fd9ff89130a682478a0c94e893ff4affe570b002
godep: error restoring dep (github.com/rakyll/globalconf): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/rakyll/goini; git checkout 907cca0f578a5316fb864ec6992dc3d9730ec58c
fatal: Referenz ist kein "Tree"-Objekt: 907cca0f578a5316fb864ec6992dc3d9730ec58c
godep: error restoring dep (github.com/rakyll/goini): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/golang.org/x/crypto/curve25519; git checkout 81bf7719a6b7ce9b665598222362b50122dfc13b
fatal: Referenz ist kein "Tree"-Objekt: 81bf7719a6b7ce9b665598222362b50122dfc13b
godep: error restoring dep (golang.org/x/crypto/curve25519): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/golang.org/x/crypto/ssh; git checkout 81bf7719a6b7ce9b665598222362b50122dfc13b
fatal: Referenz ist kein "Tree"-Objekt: 81bf7719a6b7ce9b665598222362b50122dfc13b
godep: error restoring dep (golang.org/x/crypto/ssh): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/golang.org/x/net/context; git checkout a8c61998a557a37435f719980da368469c10bfed
fatal: Referenz ist kein "Tree"-Objekt: a8c61998a557a37435f719980da368469c10bfed
godep: error restoring dep (golang.org/x/net/context): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/google.golang.org/api/google-api-go-generator; git checkout d3edb0282bde692467788c50070a9211afe75cf3
fatal: Referenz ist kein "Tree"-Objekt: d3edb0282bde692467788c50070a9211afe75cf3
godep: error restoring dep (google.golang.org/api/google-api-go-generator): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/google.golang.org/api/googleapi; git checkout d3edb0282bde692467788c50070a9211afe75cf3
fatal: Referenz ist kein "Tree"-Objekt: d3edb0282bde692467788c50070a9211afe75cf3
godep: error restoring dep (google.golang.org/api/googleapi): exit status 128
godep: Error restoring some deps. Aborting check.
rene@endor:~/CoreOS/git/endocode/fleet$ LANG=C
rene@endor:~/CoreOS/git/endocode/fleet$ ~/godep/godep restore
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/etcd/client; git checkout b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
fatal: reference is not a tree: b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
godep: error restoring dep (github.com/coreos/etcd/client): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/etcd/pkg/pathutil; git checkout b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
fatal: reference is not a tree: b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
godep: error restoring dep (github.com/coreos/etcd/pkg/pathutil): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/etcd/pkg/types; git checkout b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
fatal: reference is not a tree: b2d33e6dcb24cddc0395f1bbe2213a27aef0fb46
godep: error restoring dep (github.com/coreos/etcd/pkg/types): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/go-semver/semver; git checkout a9a0c39c7e4a2929f73d4b757d1860fbb8e66d06
fatal: reference is not a tree: a9a0c39c7e4a2929f73d4b757d1860fbb8e66d06
godep: error restoring dep (github.com/coreos/go-semver/semver): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/go-systemd/activation; git checkout 1f2251651d199b698a0be8c8bf2283178a2a97ed
fatal: reference is not a tree: 1f2251651d199b698a0be8c8bf2283178a2a97ed
godep: error restoring dep (github.com/coreos/go-systemd/activation): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/go-systemd/dbus; git checkout 1f2251651d199b698a0be8c8bf2283178a2a97ed
fatal: reference is not a tree: 1f2251651d199b698a0be8c8bf2283178a2a97ed
godep: error restoring dep (github.com/coreos/go-systemd/dbus): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/coreos/go-systemd/unit; git checkout 1f2251651d199b698a0be8c8bf2283178a2a97ed
fatal: reference is not a tree: 1f2251651d199b698a0be8c8bf2283178a2a97ed
godep: error restoring dep (github.com/coreos/go-systemd/unit): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/docker/libcontainer/netlink; git checkout 8c0303d92862eccc4bb9a07d7dac9065e4a32014
fatal: reference is not a tree: 8c0303d92862eccc4bb9a07d7dac9065e4a32014
godep: error restoring dep (github.com/docker/libcontainer/netlink): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/godbus/dbus; git checkout 9bb9dbf0e53309fa81d26e7230cbb6cff9373cad
fatal: reference is not a tree: 9bb9dbf0e53309fa81d26e7230cbb6cff9373cad
godep: error restoring dep (github.com/godbus/dbus): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/jonboulle/clockwork; git checkout b473f398c464f1988327f67c9e6aa7fba62f80d2
fatal: reference is not a tree: b473f398c464f1988327f67c9e6aa7fba62f80d2
godep: error restoring dep (github.com/jonboulle/clockwork): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/rakyll/globalconf; git checkout fd9ff89130a682478a0c94e893ff4affe570b002
fatal: reference is not a tree: fd9ff89130a682478a0c94e893ff4affe570b002
godep: error restoring dep (github.com/rakyll/globalconf): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/github.com/rakyll/goini; git checkout 907cca0f578a5316fb864ec6992dc3d9730ec58c
fatal: reference is not a tree: 907cca0f578a5316fb864ec6992dc3d9730ec58c
godep: error restoring dep (github.com/rakyll/goini): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/golang.org/x/crypto/curve25519; git checkout 81bf7719a6b7ce9b665598222362b50122dfc13b
fatal: reference is not a tree: 81bf7719a6b7ce9b665598222362b50122dfc13b
godep: error restoring dep (golang.org/x/crypto/curve25519): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/golang.org/x/crypto/ssh; git checkout 81bf7719a6b7ce9b665598222362b50122dfc13b
fatal: reference is not a tree: 81bf7719a6b7ce9b665598222362b50122dfc13b
godep: error restoring dep (golang.org/x/crypto/ssh): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/golang.org/x/net/context; git checkout a8c61998a557a37435f719980da368469c10bfed
fatal: reference is not a tree: a8c61998a557a37435f719980da368469c10bfed
godep: error restoring dep (golang.org/x/net/context): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/google.golang.org/api/google-api-go-generator; git checkout d3edb0282bde692467788c50070a9211afe75cf3
fatal: reference is not a tree: d3edb0282bde692467788c50070a9211afe75cf3
godep: error restoring dep (google.golang.org/api/google-api-go-generator): exit status 128
# cd /home/rene/CoreOS/git/endocode/fleet/Godeps/_workspace/src/google.golang.org/api/googleapi; git checkout d3edb0282bde692467788c50070a9211afe75cf3
fatal: reference is not a tree: d3edb0282bde692467788c50070a9211afe75cf3
godep: error restoring dep (google.golang.org/api/googleapi): exit status 128
godep: Error restoring some deps. Aborting check.
`
(also happens on a coreos/fleet)

Then 

`
rene@endor:~/CoreOS/git/coreos/fleet$ export PATH="$PATH:/home/rene/godep"rene@endor:~/CoreOS/git/coreos/fleet$ godep get github.com/vishvananda/netlink
`

OK, seems to have done something

`rene@endor:~/CoreOS/git/coreos/fleet$ godep save
godep: WARNING: Recorded go version (go1.4.2) with minor version string found.
godep: WARNING: Recorded major go version (go1.4) and in-use major go version (go1.5) differ.
godep: To record current major go version run `godep update -goversion`.
`

ok , let's look what it did

`
$ git diff | diffstat
 232 files changed, 2 insertions(+), 57328 deletions(-)
`

with changes like

`
diff --git a/Godeps/Godeps.json b/Godeps/Godeps.json
index a1dd174..592ea42 100644
--- a/Godeps/Godeps.json
+++ b/Godeps/Godeps.json
@@ -1,90 +1,5 @@
 {
-       "ImportPath": "github.com/coreos/fleet",
+       "ImportPath": ".",
        "GoVersion": "go1.4.2",
-       "Packages": [
-               "./..."
-       ],
-       "Deps": [
[...]
+       "Deps": []
 }
`

(removing all Packages/Deps)

**Comment by jonboulle** [comment]
@reneengelhard can you try again after #1493 ?

**Comment by reneengelhard** [comment]
(resend, sent it to the wrong PR, sorry.)

@jonboulle: I actually did already after I saw your commit but that only solves the uuid problem. The other ones still are there.

If I merge that patch and try again it doesn't work either. Since it still complains about the various stuff not a git checkout(?): So I tried the big hammer and rm -rf Godeps/_workspace/ because restore should do as it said, right.

That at least got them all. And a go get -d github.com/vishvananda/netlink works.

But a godep save -r ./... still removes everything from Godeps.json...

**Comment by jonboulle** [comment]
@reneengelhard I'm really not sure, it looks fine to me. What version of go? what version of godep? have you tried with a totally clean checkout/GOPATH?

```
 ; pwd
/tmp/fleet/src/github.com/coreos/fleet
 ; echo $GOPATH
/tmp/fleet
 ; find /tmp/fleet/ -maxdepth 4 -type d
/tmp/fleet/
/tmp/fleet/src
/tmp/fleet/src/github.com
/tmp/fleet/src/github.com/coreos
/tmp/fleet/src/github.com/coreos/fleet
 ; godep restore -v
godep: Downloading dependency (if needed): github.com/coreos/etcd/client
godep: Downloading dependency (if needed): github.com/coreos/etcd/pkg/pathutil
godep: Skipping already downloaded repo https://github.com/coreos/etcd
godep: Downloading dependency (if needed): github.com/coreos/etcd/pkg/types
godep: Skipping already downloaded repo https://github.com/coreos/etcd
godep: Downloading dependency (if needed): github.com/coreos/go-semver/semver
godep: Downloading dependency (if needed): github.com/coreos/go-systemd/activation
godep: Downloading dependency (if needed): github.com/coreos/go-systemd/dbus
godep: Skipping already downloaded repo https://github.com/coreos/go-systemd
godep: Downloading dependency (if needed): github.com/coreos/go-systemd/unit
godep: Skipping already downloaded repo https://github.com/coreos/go-systemd
godep: Downloading dependency (if needed): github.com/docker/libcontainer/netlink
godep: Downloading dependency (if needed): github.com/godbus/dbus
godep: Downloading dependency (if needed): github.com/jonboulle/clockwork
godep: Downloading dependency (if needed): github.com/pborman/uuid
godep: Downloading dependency (if needed): github.com/rakyll/globalconf
godep: Downloading dependency (if needed): github.com/rakyll/goini
godep: Downloading dependency (if needed): golang.org/x/crypto/curve25519
godep: Downloading dependency (if needed): golang.org/x/crypto/ssh
godep: Skipping already downloaded repo https://go.googlesource.com/crypto
godep: Downloading dependency (if needed): golang.org/x/net/context
godep: Downloading dependency (if needed): google.golang.org/api/googleapi
godep: Restoring dependency (if needed): github.com/coreos/etcd/client
godep: Restoring dependency (if needed): github.com/coreos/etcd/pkg/pathutil
godep: Skipping already restored repo
godep: Restoring dependency (if needed): github.com/coreos/etcd/pkg/types
godep: Skipping already restored repo
godep: Restoring dependency (if needed): github.com/coreos/go-semver/semver
godep: Restoring dependency (if needed): github.com/coreos/go-systemd/activation
godep: Restoring dependency (if needed): github.com/coreos/go-systemd/dbus
godep: Skipping already restored repo
godep: Restoring dependency (if needed): github.com/coreos/go-systemd/unit
godep: Skipping already restored repo
godep: Restoring dependency (if needed): github.com/docker/libcontainer/netlink
godep: Restoring dependency (if needed): github.com/godbus/dbus
godep: Restoring dependency (if needed): github.com/jonboulle/clockwork
godep: Restoring dependency (if needed): github.com/pborman/uuid
godep: Restoring dependency (if needed): github.com/rakyll/globalconf
godep: Restoring dependency (if needed): github.com/rakyll/goini
godep: Restoring dependency (if needed): golang.org/x/crypto/curve25519
godep: Restoring dependency (if needed): golang.org/x/crypto/ssh
godep: Skipping already restored repo
godep: Restoring dependency (if needed): golang.org/x/net/context
godep: Restoring dependency (if needed): google.golang.org/api/googleapi
godep: Checking dependency: github.com/coreos/etcd/client
godep: Checking dependency: github.com/coreos/etcd/pkg/pathutil
godep: Checking dependency: github.com/coreos/etcd/pkg/types
godep: Checking dependency: github.com/coreos/go-semver/semver
godep: Checking dependency: github.com/coreos/go-systemd/activation
godep: Checking dependency: github.com/coreos/go-systemd/dbus
godep: Checking dependency: github.com/coreos/go-systemd/unit
godep: Checking dependency: github.com/docker/libcontainer/netlink
godep: Checking dependency: github.com/godbus/dbus
godep: Checking dependency: github.com/jonboulle/clockwork
godep: Checking dependency: github.com/pborman/uuid
godep: Checking dependency: github.com/rakyll/globalconf
godep: Checking dependency: github.com/rakyll/goini
godep: Checking dependency: golang.org/x/crypto/curve25519
godep: Checking dependency: golang.org/x/crypto/ssh
godep: Checking dependency: golang.org/x/net/context
godep: Checking dependency: google.golang.org/api/googleapi
 ; godep save -r ./...
godep: WARNING: Recorded go version (go1.4.2) with minor version string found.
godep: To record current major go version run `godep update -goversion`.
 ; git status
On branch upstream-master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

**Comment by reneengelhard** [comment]
$ go version
go version go1.5.1 linux/amd64

and no, it doesn't work, still. even when doing GOPATH=/tm/fleet. And yes, when I did it the first time and it broke I did try a new clone. And this src/github.com/coreos/fleet doesn't exist in a fleet checkout. I assume /tmp/fleet was your checkout? or do you need to mimic the /src/github.com/coreos/fleet structure for the checkout to make it work?

**Comment by jonboulle** [comment]
You need to mimic the entire structure. If that's not clear from the
instructions I linked, perhaps you could suggest an improvement...

Rene Engelhard <notifications@github.com> schrieb am Mo., 14. März 2016
13:01:

**Comment by reneengelhard** [comment]
aha.

so putting our "fork" into a github.com/coreos/fleet is mandatory. oh my...

Anyways:

Let's do as you did:

```
rene@endor:~/CoreOS/git/Endocode/github.com/coreos/fleet$ pwd
/home/rene/CoreOS/git/Endocode/github.com/coreos/fleet
rene@endor:~/CoreOS/git/Endocode/github.com/coreos/fleet$ export GOPATH=~/CoreOS/git/Endocode/
rene@endor:~/CoreOS/git/Endocode/github.com/coreos/fleet$ ~/godep/godep restore -v
godep: Downloading dependency (if needed): github.com/coreos/etcd/client
godep: Downloading dependency (if needed): github.com/coreos/etcd/pkg/pathutil
godep: Downloading dependency (if needed): github.com/coreos/etcd/pkg/types
godep: Downloading dependency (if needed): github.com/coreos/go-semver/semver
godep: Downloading dependency (if needed): github.com/coreos/go-systemd/activation
godep: Downloading dependency (if needed): github.com/coreos/go-systemd/dbus
godep: Downloading dependency (if needed): github.com/coreos/go-systemd/unit
godep: Downloading dependency (if needed): github.com/docker/libcontainer/netlink
godep: Downloading dependency (if needed): github.com/godbus/dbus
godep: Downloading dependency (if needed): github.com/jonboulle/clockwork
godep: Downloading dependency (if needed): github.com/pborman/uuid
godep: Downloading dependency (if needed): github.com/rakyll/globalconf
godep: Downloading dependency (if needed): github.com/rakyll/goini
godep: Downloading dependency (if needed): golang.org/x/crypto/curve25519
godep: Downloading dependency (if needed): golang.org/x/crypto/ssh
godep: Downloading dependency (if needed): golang.org/x/net/context
godep: Downloading dependency (if needed): google.golang.org/api/googleapi
godep: Restoring dependency (if needed): github.com/coreos/etcd/client
godep: Restoring dependency (if needed): github.com/coreos/etcd/pkg/pathutil
godep: Skipping already restored repo
godep: Restoring dependency (if needed): github.com/coreos/etcd/pkg/types
godep: Skipping already restored repo
godep: Restoring dependency (if needed): github.com/coreos/go-semver/semver
godep: Restoring dependency (if needed): github.com/coreos/go-systemd/activation
godep: Restoring dependency (if needed): github.com/coreos/go-systemd/dbus
godep: Skipping already restored repo
godep: Restoring dependency (if needed): github.com/coreos/go-systemd/unit
godep: Skipping already restored repo
godep: Restoring dependency (if needed): github.com/docker/libcontainer/netlink
godep: Restoring dependency (if needed): github.com/godbus/dbus
godep: Restoring dependency (if needed): github.com/jonboulle/clockwork
godep: Restoring dependency (if needed): github.com/pborman/uuid
godep: Restoring dependency (if needed): github.com/rakyll/globalconf
godep: Restoring dependency (if needed): github.com/rakyll/goini
godep: Restoring dependency (if needed): golang.org/x/crypto/curve25519
godep: Restoring dependency (if needed): golang.org/x/crypto/ssh
godep: Skipping already restored repo
godep: Restoring dependency (if needed): golang.org/x/net/context
godep: Restoring dependency (if needed): google.golang.org/api/googleapi
godep: Checking dependency: github.com/coreos/etcd/client
godep: Checking dependency: github.com/coreos/etcd/pkg/pathutil
godep: Checking dependency: github.com/coreos/etcd/pkg/types
godep: Checking dependency: github.com/coreos/go-semver/semver
godep: Checking dependency: github.com/coreos/go-systemd/activation
godep: Checking dependency: github.com/coreos/go-systemd/dbus
godep: Checking dependency: github.com/coreos/go-systemd/unit
godep: Checking dependency: github.com/docker/libcontainer/netlink
godep: Checking dependency: github.com/godbus/dbus
godep: Checking dependency: github.com/jonboulle/clockwork
godep: Checking dependency: github.com/pborman/uuid
godep: Checking dependency: github.com/rakyll/globalconf
godep: Checking dependency: github.com/rakyll/goini
godep: Checking dependency: golang.org/x/crypto/curve25519
godep: Checking dependency: golang.org/x/crypto/ssh
godep: Checking dependency: golang.org/x/net/context
godep: Checking dependency: google.golang.org/api/googleapi
rene@endor:~/CoreOS/git/Endocode/github.com/coreos/fleet$ go get -d github.com/vishvananda/netlink
$ ~/godep/godep save -r ./...
godep: WARNING: Recorded go version (go1.4.2) with minor version string found.
godep: WARNING: Recorded major go version (go1.4) and in-use major go version (go1.5) differ.
godep: To record current major go version run `godep update -goversion`.
```

No error. Still the same diff. Everything removed.

**Comment by jonboulle** [comment]
Your pwd is wrong. It should be $GOPATH/*src*/github.com/coreos/fleet

**Comment by reneengelhard** [comment]
ok, yeah, my bad. now I unbderstand this logic. the hardcoding of githiub.com/coreos/fleet (imho) makes sharing stuff in $GOPATH impossible because you then can't have two fleet repos there directly (coreso/fleet and endocode/fleet), but anways...

Now it works. Pushed (with --force).

(Now I also got some "artifiicial"(?) stuff which I added in a separate commit. Maybe some missed (automatic) changes in the past?

**Comment by reneengelhard** [comment]
@jonboulle ping? :) This should be able to be merged now, shouldn't it? (Maybe excluding cd0322ecbac640cbac640cbac640?)

**Comment by jonboulle** [comment]
This looks good (I think that commit is just a change in godep working, so it's now more specific with subpackages). Can you clean up the commit history  before merging? thanks

**Comment by reneengelhard** [comment]
@jonboulle: hmm? AFAICS the commit history _is_ clean. It has

a) onlyjobs patch, and I don't want to squash it given it'd loose his authorship info
b) your uuid fix
c) the actual copying of the new module in-tree
d) the automatic godep change

which imho should also be in commits like this so see what was done.

**Comment by antrik** [comment]
@reneengelhard that's now what a clean history means. A clean history only should describe the logical changes that happen between the previous master and the new master -- how you *arrived* at these changes is irrelevant in the long run.

Notably, history should always be "bisectable", i.e. when picking a random commit -- even from the middle of a pull request -- the code should never have (known) regressions compared to previous versions. I haven't tried to verify this, but I tend to doubt this would be the case with the history as it is now...

As for authorship: isn't the author of the first commit preserved by default when squashing?

**Comment by reneengelhard** [comment]
@antrik as discussed I believe this is wrong, but pushed now squashed anyway. 

I can understand the bibisect argument, yes. And I can understand the "make your commit self-contained" argument. Which is why a) and c) probably should be squashed.

But a) and d) are different. a) is not from onlyjob but from jonboulle. and d) is a automatic tool change.

And: What if more people contributed together? Author: would be wrong. (here it would work as Author: is onlyjob, but...)

And yes, preserving authorsip IS important for copyright.

**Comment by reneengelhard** [comment]
rebased..

**Comment by jonboulle** [comment]
Agh, sorry for the confusion. I was referring mostly to the commit messages - but also that the two godep ones could be squash together. I agree that onlyjob's should be split out..

**Comment by reneengelhard** [comment]
@jonboulle ok, fixed

**Comment by jonboulle** [comment]
Oh no, something happened and the new dep fell out :-(

**Comment by reneengelhard** [comment]
@jonboulle: yeah. I could have sworn I did check that. Ah, well. now, finally...

Now the functional tests fail (whereas they succeeded when it was done and initially pushed), but succeed on master... :(

**Comment by jonboulle** [comment]
Weird.. Kicked semaphore again. I wonder if it was a flake related to #1512

**Comment by jonboulle** [comment]
@reneengelhard thanks for your patience, lgtm!

**Pull request merged**
