### PR TITLE
Use upstream etcd client

### LINKED ISSUE #1209: Replace fleet/etcd with github.com/coreos/etcd/client
The etcd client in fleet/etcd was a bandaid for the trouble we had with go-etcd. Now that the fleet/etcd client has effectively moved into github.com/coreos/etcd/client (and improved a lot!), fleet should just switch to that new client.

### PR DESCRIPTION
**Pull request by bcwaldon**
Closes #1209

### CODE REVIEW

**Comment by ecnahc515** [comment]
@bcwaldon Are you just looking for a general review of things here?

**Comment by bcwaldon** [comment]
@ecnahc515 yep, that would be great

**Comment by ecnahc515** [comment]
Things seem to be good. You might wait until https://github.com/coreos/etcd/pull/2913 gets merged because it fixed a bug in canceling watcher contexts that I found. Then you can update the dependency.

Otherwise, it looks good, and everything looks like it was translated properly.

**Comment by xiang90** [comment]
@ecnahc515 It already gets merged into etcd/client.

**Comment by ecnahc515** [comment]
Great, sounds good then.

**Pull request merged**
