### PR TITLE
fleet binary accidentally invoked instead of fleetctl

### PR DESCRIPTION
**Pull request by jonboulle**
reported by @normelton https://gist.github.com/normelton/6b597287e791b5b3be26
At first glance it doesn't harm but aesthetically doesn't look good.

probably we have to add command interpreter

### CODE REVIEW

**Comment by jonboulle** [comment]
PTAL

**Comment by kayrus** [comment]
LGTM

**Comment by tixxdz** [comment]
Hi @jonboulle, having to check external arguments of another program may add an extra burden on us, so I just created this PR https://github.com/coreos/fleet/pull/1413

It seems that bug was already fixed by another commit, so it is already backward incompatible.

Thanks

**Comment by jonboulle** [comment]
Closing in favour of #1413

**Pull request closed without merging**
