### PR TITLE
vendor: switch to go vendoring

### LINKED ISSUE #1536: build: replace gopdep with vendor
abandon golang 1.4 support and replace godep with vendor.
@tixxdz @antrik @jonboulle comments?

### PR DESCRIPTION
**Pull request by kayrus**
resolves #1536
obsoletes #1537

Not sure whether I did that correctly... Here are my steps:

```sh
find . -name '*.go' -exec sed -i 's#github.com/coreos/fleet/Godeps/_workspace/src/##g' {} \;
cat Godeps/Godeps.json | grep -v github.com/coreos/fleet | awk -F"[:\", \t]*" '/ImportPath|Rev/ { if ($2 == "ImportPath") { printf("%s ",$3) } else { printf("%s\n",$3)} }' > vendor.manifest
git add vendor.manifest
mkdir vendor
git mv Godeps/_workspace/src/* vendor/
git rm -r Godeps
go fmt registry/fake.go
```

Then fixed:

* .travis.yml - add new env
* build-env - remove legacy support for go 1.4

### CODE REVIEW

**Comment by reneengelhard** [comment]
looks good to me, at least it still builds, CI works, etc :)

**Comment by dongsupark** [comment]
Looks good. My local build also works.

**Comment by dongsupark** [comment]
After talking to hector and kayrus, we agreed that we'd need to merge this PR to avoid further pain.

**Comment by hectorj2f** [comment]
+1, It would make the live easier to merge new PRs which require additional go libraries. :)

**Comment by dongsupark** [comment]
Merged. Thanks.

**Pull request merged**
