### PR TITLE
build: secured CDIR variable, now should work with spaces in path

### PR DESCRIPTION
**Pull request by kayrus**

### CODE REVIEW

**Comment by dongsupark** [comment]
Generally I think it's a good idea.
But functional test's build is always failing with:
```
can't load package: package github.com/coreos/fleet/functional: cannot find package "github.com/coreos/fleet/functional" in any of:
	/home/core/go/src/github.com/coreos/fleet/functional (from $GOROOT)
	/home/core/fleet/functional/gopath/src/github.com/coreos/fleet/functional (from $GOPATH)
```

Interesting.

**Comment by dongsupark** [comment]
Ok, the build error happens because both ``functional/test`` and ``build-env`` try to define a variable ``${CDIR}``, although ``functional/test`` sources ``build-env``. You need to rename ``${CDIR}`` into another name, either in ``functional/test`` or ``build-env``. I think a correct fix would be to update ``build-env``, as that's also imported by other files.

**Comment by kayrus** [comment]
fixed in other way. just use `CDIR=$(cd `dirname "$0/.."` && pwd)`

**Comment by dongsupark** [comment]
LGTM

**Pull request merged**
