### PR TITLE
functional: allow run-in-qemu to run based on a custom base image

### PR DESCRIPTION
**Pull request by dongsupark**
Allow run-in-qemu to run with a given custom base image, e.g. ``coreos_developer_qemu_image.img`` which was built by CoreOS SDK.

```
  $ ./run-in-qemu -c alpha -i ~/.qemu/coreos_developer_qemu_image.img
```

/cc @kayrus

### CODE REVIEW

**Comment by kayrus** [comment]
@dongsupark I'd suggest only to use double hyphens for long format options.

**Comment by dongsupark** [comment]
@kayrus Agreed. I'm wondering too, why the script wasn't written with double hyphens in the first place.

**Comment by dongsupark** [comment]
Updated.
* used double hyphens for long options.
* renamed developer image to base image.

**Comment by kayrus** [comment]
@dongsupark LGTM

**Comment by jonboulle** [comment]
lgtm

**Comment by dongsupark** [comment]
Merged https://github.com/coreos/fleet/pull/1590. Thanks.

**Pull request merged**
