### PR TITLE
fleetctl: more tests for start load command and template path

### PR DESCRIPTION
**Pull request by tixxdz**
Add more tests for fleetctl start and load commands, and make sure that the template unit path also works as expected. While we are it improve fleetctl test helper functions.

### CODE REVIEW

**Comment by tixxdz** [comment]
@dongsupark thank you, done!

**Comment by dongsupark** [comment]
@tixxdz looks good. :-)
I'm going to try to run these tests today, as soon as my test setup got cleaned up.

**Comment by tixxdz** [comment]
@jonboulle ok hold on this one, I opened new PR for load https://github.com/coreos/fleet/pull/1464 and new ones are coming, will close this one after that.

**Comment by tixxdz** [comment]
@jonboulle second one https://github.com/coreos/fleet/pull/1465  ,and the next one will be on top

Thank you!

**Comment by tixxdz** [comment]
@dongsupark @jonboulle last series of this patches is here: https://github.com/coreos/fleet/pull/1466

**Comment by tixxdz** [comment]
The first two PRs were merged, the last ons is #1466 , so closing

**Pull request closed without merging**
