### PR TITLE
Add a document about scaling fleet

### PR DESCRIPTION
**Pull request by miekg**
As requested by @bcwaldon, this is the start of a scaling doc.

### CODE REVIEW

**Comment by robszumski** [comment]
Is this an RFC? If so, can we label it as such?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [fleet] Add a document about sc..." ]
>Is this an RFC? If so, can we label it as such?

RFC as request for comments? Or Change?

But yeah, sure. How do I label it?

/Miek

--
Miek Gieben

**Comment by jonboulle** [comment]
Fixed by #1353, sorry for the delay.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [fleet] Add a document about sc..." ]
>Fixed by #1353, sorry for the delay.

Nice. Thanks.

**Pull request closed without merging**
