### PR TITLE
fleetd: support operators in metadata

### LINKED ISSUE #1143: Operators in Metadata
Would the authors consider allowing operators in metadata?

ie:

[X-fleet]
MachineMetadata=ram>=2048

This + way to update metadata easier = dynamic metadata, awesome? lame? opinions?

thanks

### PR DESCRIPTION
**Pull request by wuqixuan**
If define metadata in fleet conf, such as "ram=1024", we can
define the operator in [X-Fleet] unit as below:
[X-Fleet]
MachineMetadata=ram>=2048
The operators have been supported: "<=", ">=", "!=", "<", ">", "="
If the operatior are "<=", ">=", "!=", "<", ">", the value should
be integer, otherwise, the unit will never be launched.

Fixes #1143

### CODE REVIEW

**Comment by bcwaldon** [comment]
1. I'd like to see the operator `==` defined (equivalent to the existing `=`)
2. we need significant testing of these new operators
3. both the API and fleetctl need to validate metadata against these new rules

**Comment by mwitkow-io** [comment]
This would be awesome :)

**Comment by osterman** [comment]
Really looking forward to this!

**Comment by dongsupark** [comment]
Closed in favor of https://github.com/coreos/fleet/pull/1632. Thanks.

**Pull request closed without merging**
