### PR TITLE
build: fixed docker-based scripts

### PR DESCRIPTION
**Pull request by kayrus**
supersedes #1543

### CODE REVIEW

**Comment by tixxdz** [comment]
lgtm!

**Comment by tixxdz** [comment]
one moment, @kayrus could you please edit the commit log and say why we need this change!

**Comment by kayrus** [comment]
This PR caused another minor issue: https://github.com/coreos/fleet/issues/1547

**Comment by tixxdz** [comment]
Hi that issue #1547 is not caused by this PR, but by this merged patch https://github.com/coreos/fleet/commit/98f185061c0085719566ad385d85bb430e014784 where inside test-docker you instruct it to run under the specified user `-u switch`

Anyway that issue #1547 should be fixed on its own with https://github.com/coreos/fleet/pull/1548

Thanks!

**Pull request merged**
